
services:
  nginx:
    image: nginx:stable-alpine
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - net

  db:
    image: postgres:latest
    container_name: "db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: articles
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - net

  app:
    build: 
      context: .
    container_name: "app"
    environment:
      DATABASE_URL: postgresql://postgres:1337@db:5432/articles
    ports:
      - "8000:8000"  # Порт вашего приложения
    depends_on:
      - db
    restart: always
    networks:
      - net

volumes:
  postgres_data:

networks:
  net:
